### ISSUE TITLE
CSV Format

### ISSUE THREAD

**Issue by GabrielLin** [MLNLP-World/Top-AI-Conferences-Paper-with-Code#2]
Great work! Could you please provide a table format data like CSV? Thanks.

**Comment by yizhen20133868** [comment]
ok, thanks for your kind mention. We will leave it as future work. Actually, we have the pdf version, which will be released soon.

**Comment by qinlibo-hit** [comment]
> Great work! Could you please provide a table format data like CSV? Thanks.

ok, thanks for your kind mention. We will leave it as future work. Actually, we have the pdf version, which will be released soon.
